/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   lib/legacy/polymer-fn.js
 */

import {Class} from './class.js';


/**
 * Legacy class factory and registration helper for defining Polymer
 * elements.
 *
 * This method is equivalent to
 *
 *     import {Class} from '/local/community/mod/circle-sensor-card-depends/@polymer/polymer/lib/legacy/class.js';
 *     customElements.define(info.is, Class(info));
 *
 * See `Class` for details on valid legacy metadata format for `info`.
 *
 * @returns Generated class
 */
declare function Polymer(info: PolymerInit): {new(): HTMLElement};

export {Polymer};

import {PolymerInit} from '../../interfaces';
