binary_sensor:
  - platform: command_line
    name: monitors_mute_state
    scan_interval: 86400
    command: !secret monitors_mute_state
    payload_on: 'true'
    payload_off: 'false'
    device_class: sound

  - platform: ping
    name: nas_internet_access
    host: 8.8.8.8

  - platform: ping
    name: rpi_ping
    host: !secret rpi_ping_host
