# yamllint disable rule:document-start

resources:
  - url: /local/custom_cards/icloud3-event-log-card.js?v=1.001
    type: js

title: Home
views:

  # ==========================================================
  - title: iCloud Event Log
    icon: mdi:information-outline
    cards:
      - type: custom:icloud3-event-log-card
        entity: sensor.icloud3_event_log
