# yamllint disable rule:document-start

title: Home
views:
  - title: Location
    icon: mdi:cellphone-iphone
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            title: Location Info - Gary
            column_width: 25%
            entities:
              - entity: device_tracker.gary_iphone
                name: Gary
              - entity: sensor.gary_iphone_interval
                name: Interval
                icon: mdi:clock-start
              - entity: sensor.gary_iphone_travel_time
                name: TravTime
                icon: mdi:clock-outline
              - entity: sensor.gary_iphone_zone_distance
                name: HomeDist
                icon: mdi:map-marker-distance

          - type: glance
            column_width: 25%
            entities:
              - entity: sensor.gary_iphone_waze_distance
                name: WazeDist
                icon: mdi:map-marker-distance
              - entity: sensor.gary_iphone_calc_distance
                name: CalcDist
                icon: mdi:map-marker-distance
              - entity: sensor.gary_iphone_dir_of_travel
                name: Direction
                icon: mdi:compass-outline
              - entity: input_boolean.gary_driving_flag
                name: Driving
                tap_action:
                  action: toggle

          - type: glance
            column_width: 25%
            entities:
              - entity: sensor.gary_iphone_last_located
                name: Located
                icon: mdi:history
              - entity: sensor.gary_iphone_last_update
                name: LastUpdt
                icon: mdi:history
              - entity: sensor.gary_iphone_next_update
                name: NextUpdt
                icon: mdi:update
              - entity: sensor.gary_iphone_poll_count
                name: PollCount
                icon: mdi:counter

          - type: entities
            entities:
              - entity: sensor.gary_iphone_info
                name: Info
                icon: mdi:information-outline

          - type: entities
            entities:
              - script.icloud3_update_location_gary
              - script.homeassistant_restart

  # -------------------------------------------------------------------
  - title: iCloud Event Log
    icon: mdi:information-outline
    cards:
      - type: custom:icloud3-event-log-card
        entity: sensor.icloud3_event_log
